### ISSUE TITLE
Generic PDE Terms

### ISSUE THREAD

**Issue by jejjohnson** [jejjohnson/jaxsw#16]
This will feature some fairly generic PDE terms that keep cropping up that we may want to solve.

## Diffusion

> Some generic Diffusion equation `ν (∂²η/∂x² + ∂²η/∂y²)` that we may want to solve 

$$
\begin{aligned}
&=\nu \left( \frac{\partial^2 \eta}{\partial x^2} + \frac{\partial^2 \eta}{\partial y^2} + \frac{\partial^2 \eta}{\partial z^2}\right)
\end{aligned}
$$

* [x] Naive
  * [x] 1D
  * [x] 2D

## Advection

> Some generic advection terms that we may want to solve, i.e. `u ∂η/∂x + v ∂η/∂y + w ∂η/∂z`

$$
\begin{aligned}
&=u \frac{\partial \eta}{\partial x} + v \frac{\partial \eta}{\partial y} + w \frac{\partial \eta}{\partial z}
\end{aligned}
$$

* [x] Naive
  * [x] 1D
  * [x] 2D
* [x] Upwind
  * [x] 1D
  * [x] 2D
* [ ] #21

**Note**: I've also seen instantiations of this with the name "determinant Jacobian".

**Comment by roxyboy** [comment]
I think the generic advection term should read `u da/dx + v db/dy` as advection always entails a gradient of 'something' being transported by u and v.

**Comment by jejjohnson** [comment]
Makes sense. But wouldn’t the a b (and c) be the same variable? Mainly the advection term from the definition of the Jacobian/advection term part? 

I think I was a naive with the “generic advection term” label because I did it thinking about the tutorial not the actual PDEs, e.g. [shallow water](https://en.wikipedia.org/wiki/Shallow_water_equations), [QG](https://en.wikipedia.org/wiki/Vorticity_equation), etc.

**Comment by jejjohnson** [comment]
Closing due to #22 and #20
